
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monochat
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: monochat-rails=ghcr.io/kurazuuuuuu/monochat-rails
    argocd-image-updater.argoproj.io/monochat-rails.update-strategy: semver
    argocd-image-updater.argoproj.io/monochat-rails.pull-secret: pullsecret:argocd/ghcr-registry-secret
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-repository: https://github.com/kurazuuuuuu/monochat.git
    argocd-image-updater.argoproj.io/write-back-target: kustomization
    argocd-image-updater.argoproj.io/git-repository-credentials: argocd:git-creds
    argocd-image-updater.argoproj.io/git-branch: main
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/kurazuuuuuu/monochat
    path: k8s-manifests
    targetRevision: main
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 3