apiVersion: apps/v1
kind: Deployment
metadata:
  name: monochat-rails
  namespace: argocd-prod
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: monochat-rails
  template:
    metadata:
      labels:
        app: monochat-rails
    spec:
      imagePullSecrets:
      - name: ghcr-registry-secret
      containers:
      - name: monochat-rails
        image: ghcr.io/kurazuuuuuu/monochat-rails:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: RAILS_ENV
          valueFrom:
            secretKeyRef:
              name: monochat-secrets
              key: rails-env
---
apiVersion: v1
kind: Service
metadata:
  name: monochat-rails-external
  namespace: argocd-prod
spec:
  selector:
    app: monochat-rails
  ports:
  - port: 3000
    targetPort: 3000
  type: LoadBalancer
  loadBalancerIP: 192.168.1.29
